In [1]:
import numpy as np

In [5]:
araay = np.array([1,2,3,4,5,6]).reshape(2,3)
araay

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
aran = np.arange(15).reshape(5,3)
aran

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
one = np.ones([4,3], dtype=np.int)
one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
zero = np.zeros([2,6], dtype=np.int)
zero

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [23]:
empt = np.empty([14, 3])
empt

array([[1.04662129e-311, 1.04659368e-311, 1.04663744e-311],
       [1.04663744e-311, 1.04663743e-311, 1.04663744e-311],
       [1.04663744e-311, 1.04663743e-311, 1.04663744e-311],
       [1.04663743e-311, 1.04663744e-311, 1.04663744e-311],
       [1.04663743e-311, 1.04663744e-311, 1.04663744e-311],
       [1.04663744e-311, 1.04663744e-311, 1.04663744e-311],
       [1.04663742e-311, 1.04663744e-311, 1.04663744e-311],
       [1.04663744e-311, 1.04663744e-311, 1.04663744e-311],
       [1.04663743e-311, 1.04663744e-311, 1.04663744e-311],
       [1.04663742e-311, 1.04663744e-311, 1.04663743e-311],
       [1.04663744e-311, 1.04663744e-311, 1.04663743e-311],
       [1.04663744e-311, 1.04663744e-311, 1.04663744e-311],
       [1.04663744e-311, 1.04663744e-311, 1.04663742e-311],
       [1.04663744e-311, 1.04663743e-311, 1.04663744e-311]])

In [26]:
fulla = np.full([3,4], 33)
fulla

array([[33, 33, 33, 33],
       [33, 33, 33, 33],
       [33, 33, 33, 33]])

In [27]:
# likes
np.asarray([x for x in range(13)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
np.zeros_like(araay)

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
np.ones_like(araay)

array([[1, 1, 1],
       [1, 1, 1]])