In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
npList = np.array([1, 2, 3, 4])
npList = npList * 2
print(npList)

[2 4 6 8]


In [13]:
print(hex(id(npList[0])))
print(hex(id(npList[1])))
print(hex(id(npList[2])))
print(hex(id(npList[3])))

# All elements are at the same position ... 

0x730a779138
0x730a779138
0x730a779138
0x730a779138


### How to check number of lines in a csv file ?

In [69]:
npZero = np.zeros(5)  #if next operation is addition as zero is additive identity
npZeros = np.zeros([2, 2]) # Multi-dimensional zero array
npOne = np.ones(6)    #if next operation is multiplication as one is multiplicative identity
print("Np Zero :\n", npZero)
print("Np Zeros :\n", npZeros)
print("Np One :\n", npOne)

print("__________________________\n")
print("Shape of npZeros :", npZeros.shape)
print("Dimension of npZeros :", npZeros.ndim)
print("Data Type of npZeros :", npZeros.dtype)

Np Zero :
 [0. 0. 0. 0. 0.]
Np Zeros :
 [[0. 0.]
 [0. 0.]]
Np One :
 [1. 1. 1. 1. 1. 1.]
__________________________

Shape of npZeros : (2, 2)
Dimension of npZeros : 2
Data Type of npZeros : float64


In [74]:
npEmpty = np.empty(6) # produces an array of garbage values 
npArange = np.arange(0, 5, 1)
print(npEmpty)
print(npArange)

[1. 1. 1. 1. 1. 1.]
[0 1 2 3 4]


### Attributes Of Numpy Array :
- Shape : A tuple indicating the size of each dimension
- dtype : An object describing the data type of the array
- ndim : the number of dimensions of the array

In [70]:
npOneInt = np.ones(5, dtype = int)
print(npOneInt)

[1 1 1 1 1]


In [76]:
sum(npEmpty)

6.0

In [80]:
npZeros.reshape(4)

array([0., 0., 0., 0.])

In [3]:
import numpy as np
my_arr = np.arange(1000000)
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 43 ms


# PRACTICE WITH HASHTECH And HR

In [4]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
list1 = list([1,2,3,4,5])
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [7]:
list1 = []
for i in range(0,20):
    list1.append(i)
list1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [8]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
arr2 = np.arange(100000)
arr2

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [11]:
arr3 = np.asarray([1,2,3,4,5]) #asarray dont make copy , copy=False
arr3

array([1, 2, 3, 4, 5])

In [13]:
d = np.array(list1,dtype="float32") #np.int8, int32
d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.], dtype=float32)

In [17]:
d = np.asarray(list1,dtype=np.float32) #np.int8, int32
d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.], dtype=float32)

In [19]:
d = np.asarray(list1,dtype='f8') #np.int8, int32
d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [20]:
#array, asarray, arange,one,zero

In [21]:
one = np.ones(12)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
zero = np.zeros(12)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# SHAPE, DIMENSION

In [7]:
twoD = np.array([[1,2,3],[3,4,5]])
twoD

array([[1, 2, 3],
       [3, 4, 5]])

In [9]:
twoD.shape

(2, 3)

In [19]:
threeD = np.array([[[1,2,3],[4,5,6],[7,8,3]]])
threeD

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 3]]])

In [20]:
threeD.shape

(1, 3, 3)

In [22]:
fourD = np.array([[[ [1,2,3],[4,5,6] ]]])

In [23]:
fourD

array([[[[1, 2, 3],
         [4, 5, 6]]]])

In [24]:
fourD.shape

(1, 1, 2, 3)

In [26]:
fourD.ndim

4

In [29]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [31]:
print(hex(id(arr[0])))
print(hex(id(arr[1])))

0x3988b15ab0
0x3988b15ab0


In [33]:
list1 = list([1,2,3,4,5])
print(hex(id(list1[0])))
print(hex(id(list1[1])))

0x7ffaf97f9340
0x7ffaf97f9360


In [39]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
arr = np.arange(10).reshape(5,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [46]:
arr = np.arange(0,36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

#ravel #flatten

In [49]:
arr = np.ravel(arr)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [50]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [48]:
arr = arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

# INDEXING AND SLICING

In [52]:
list1 = [1,2,3,4,5]
type(list1[1])

int

In [54]:
type(list1[1:3])

list

In [55]:
arr = np.arange(0,36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [56]:
arr[2][3]

15

In [62]:
#array[startrow:lastrow+1,startcolumn:lastcolumn+1]
arr[2:3,2:4]

array([[14, 15]])

In [61]:
arr[2:4,1:2]

array([[13],
       [19]])

In [64]:
arr[1:2,2:4]

array([[8, 9]])

In [66]:
arr[4:,4:5]

array([[28],
       [34]])

In [68]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [74]:
arr[-2:,-2:-1]

array([[28],
       [34]])

In [76]:
arr[-2:-1,-6:-3]

array([[24, 25, 26]])

In [81]:
arr[0:6,0:6:2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [82]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [86]:
arr[::2,:]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [88]:
arr[1:6:2,:]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23],
       [30, 31, 32, 33, 34, 35]])

In [100]:
arr3d = np.array([ [[100,200,300],[400,500,600],[700,800,900]] ])
arr3d

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [103]:
arr3d[0][1]

array([400, 500, 600])

In [104]:
arr3d[0,1]

array([400, 500, 600])

In [105]:
arr3d[0,1,1]

500

In [106]:
arr4d = np.array([ [ [[1,2,3],[3,4,5],[6,7,8]] ] ])
arr4d

array([[[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]]])

In [107]:
arr4d[0,0,1,0]

3

In [108]:
#array,asarray,ones,zeros,full,ones_like,zeros_like,empty,linspace,logspace

In [115]:
one = np.ones([1,3,3])
one.ndim

3

In [122]:
onel = np.ones_like(arr4d)
onel

array([[[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]]])

In [126]:
emp = np.empty((3,3))
emp

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [128]:
fil = np.full([3,3],4)
fil

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [132]:
di = np.eye(3,3)
di

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [138]:
lin = np.linspace(0,16,16) #last is included
lin

array([ 0.        ,  1.06666667,  2.13333333,  3.2       ,  4.26666667,
        5.33333333,  6.4       ,  7.46666667,  8.53333333,  9.6       ,
       10.66666667, 11.73333333, 12.8       , 13.86666667, 14.93333333,
       16.        ])

In [135]:
lo = np.logspace(0,8,2) #last is included
lo

array([1.e+00, 1.e+08])

In [139]:
m1 = np.matrix('1 2 3 ; 4 5 6')
m1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [143]:
m1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
m1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [144]:
m1+m1

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [145]:
m1*m1 #no of columns of first = no of rows of second

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [150]:
m1@m1

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [146]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
m1+m1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [148]:
m1*m1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [149]:
m1@m1 #common matrix multiplication

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [151]:
m1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [153]:
np.transpose(m1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [154]:
1/m1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [155]:
m1*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [160]:
from numpy import *
Arr = arange(1,16,2) #15-1
myArr = array([1,2,3,4,5,6])
print(Arr)
print(sin(Arr))
print(log(Arr))
print(sqrt(Arr))
print(sum(Arr))
print(min(Arr))
print(max(Arr))
print(sort(Arr))
print(concatenate([myArr,Arr]))

[ 1  3  5  7  9 11 13 15]
[ 0.84147098  0.14112001 -0.95892427  0.6569866   0.41211849 -0.99999021
  0.42016704  0.65028784]
[0.         1.09861229 1.60943791 1.94591015 2.19722458 2.39789527
 2.56494936 2.7080502 ]
[1.         1.73205081 2.23606798 2.64575131 3.         3.31662479
 3.60555128 3.87298335]
64
1
15
[ 1  3  5  7  9 11 13 15]
[ 1  2  3  4  5  6  1  3  5  7  9 11 13 15]


np.where(condition,option A(if condition is true),option B(when false))

In [161]:
salary = array([-1,-2,-3,2500,3000,3500])
where(salary>0,1,0)

array([0, 0, 0, 1, 1, 1])

In [162]:
arr = array([1,2,3,1,3,4,1,2,43,4])
arr = unique(arr)
arr

array([ 1,  2,  3,  4, 43])

In [1]:
import numpy as np

In [35]:
arr = np.arange(24).reshape(6,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
#dir(arr)

In [41]:
zerli = np.zeros_like(arr) #it gives arr with 0
zerli

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
arr = np.ones([5,4],dtype="int32") # ones([rows, columns])
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
arr = np.zeros([5,4],dtype=np.int32) # ones([rows, columns])
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
arr = np.empty([5,4],dtype="int32") # ones([rows, columns])
arr

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 4718684, 6029424],
       [6619204, 7012467, 7274612, 6029424],
       [6881389, 6815844, 2949217, 4784193],
       [2752604, 2752558, 3014656, 7536746]])

In [22]:
arr = np.empty([5,4]) # ones([rows, columns])
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
arr = np.ones([5,4],dtype="u8")
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=uint64)

In [45]:
a1 = np.full([5,4],4)
a1

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [60]:
a2 = np.full_like(arr, np.random.randint(1,10))
a2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [69]:
ide = np.eye(5,7) # size dena hay bas directly
ide

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [72]:
idem = np.identity(6) # jo size de gay us ko size x size de de ga 
idem

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [77]:
aran = np.arange(10).reshape(5,2)
aran

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [83]:
asar = np.asarray([1,2,3,4,5])
asar

array([1, 2, 3, 4, 5])