In [1]:
import numpy as np

In [3]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
hs = np.split(a,[2],axis=1)
hs

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [20]:
np.random.randn(15).reshape(3,5)

array([[ 0.42241593,  0.41475555,  1.14353222,  0.37436414, -0.42878843],
       [ 0.53849796, -0.34820343,  0.29145404, -1.59782293,  1.35977171],
       [-1.53353342,  0.18557148,  2.04406285,  2.4608038 ,  1.82016495]])

In [22]:
slicer = np.arange(30).reshape(5,3,2)
slicer

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [25]:
slicer.shape

(5, 3, 2)

In [27]:
slicer[3:4,0:1,:] #all indices have a maximum value as in shape 

array([[[18, 19]]])

In [29]:
arr = np.arange(16).reshape(2,2,2,2)
arr

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [30]:
arr.shape

(2, 2, 2, 2)

# Hurray! I m a slicing champ 😍

In [37]:
arr[1:2,:2,1:2,:2]  

array([[[[10, 11]],

        [[14, 15]]]])

In [40]:
x = np.array([
              [1,2,3],
              [4,5,6],
             ]
            )
x

array([[1, 2, 3],
       [4, 5, 6]])

# The game of Transpose 🙄

In [41]:
x.transpose() # rows to columns and vice versa

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
arr = np.arange(27).reshape(3,3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [45]:
arr.transpose() 

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

#### The primary functional difference is that flatten is a method of an ndarray object and hence can only be called for true numpy arrays. In contrast ravel() is a library-level function and hence can be called on any object that can successfully be parsed.
😎