In [3]:
import numpy as np

# lingua franca for data exchange

In [31]:
l=range(1000000) #a python list of 1000000 numbers

In [10]:
d=np.arange(1000000) #a numpy array

In [ ]:
%time for _ in range(1000000): r=[x*2 for x in l]

In [ ]:
%time for _ in range(1000000): r=d*2

In [13]:
# Numpy is based on nd-array

In [20]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 3.26083326e-321],
       [1.78020983e-306, 8.34454049e-308, 2.29179042e-312]])

In [32]:
l=[1,4,5,7]
np.array(l)

array([1, 4, 5, 7])

In [35]:
x=np.arange(1,100,10) #similar to range method

In [36]:
x.shape

(10,)

In [42]:
y=np.zeros((10,10))
y.shape

(10, 10)

In [47]:
y=y.reshape((2,2,5,5))
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [48]:
y.dtype

dtype('float64')

In [49]:
y.ndim

4

In [50]:
#Arithmetic Operations

In [51]:
a = np.random.randn((10))
b = np.random.randn((10))
print(a, b)

[ 0.38084329 -0.05526375  2.5790815  -1.23333402  0.09141584 -1.0096546
  1.27520199  0.45605031  1.08035419  0.88932789] [ 2.02430924  0.99083482  1.22443074  2.00601984 -0.01712458 -1.77294108
  0.4333534   0.14562043  1.93772417  0.07086354]


In [52]:
a+b

array([ 2.40515253,  0.93557107,  3.80351224,  0.77268582,  0.07429126,
       -2.78259568,  1.7085554 ,  0.60167074,  3.01807836,  0.96019143])

In [53]:
a-b

array([-1.64346595, -1.04609858,  1.35465076, -3.23935387,  0.10854042,
        0.76328649,  0.84184859,  0.31042989, -0.85736997,  0.81846435])

In [54]:
a/b

array([ 0.18813494, -0.05577494,  2.10635148, -0.61481646, -5.33828096,
        0.56948006,  2.94263756,  3.13177434,  0.55753766, 12.54986504])

In [55]:
a*b

array([ 7.70944597e-01, -5.47572523e-02,  3.15790666e+00, -2.47409252e+00,
       -1.56545820e-03,  1.79005812e+00,  5.52613122e-01,  6.64102408e-02,
        2.09342843e+00,  6.30209247e-02])

In [59]:
1/a

array([  2.6257519 , -18.09504282,   0.38773494,  -0.81081036,
        10.93902332,  -0.99043772,   0.78418949,   2.19274052,
         0.92562236,   1.12444466])

In [60]:
a>0 # which elements satisfy the condition

array([ True, False,  True, False,  True, False,  True,  True,  True,
        True])

In [61]:
a[a>0] #elements based on condition

array([0.38084329, 2.5790815 , 0.09141584, 1.27520199, 0.45605031,
       1.08035419, 0.88932789])

In [64]:
# Indexing and Slicing

In [62]:
arr = np.array([1,7,9,8,5])

In [63]:
arr[4]

5

In [66]:
arr[arr>5] #boolean indexing 

array([7, 9, 8])

In [67]:
arr[[2,1]] #fancy indexing

array([9, 7])

In [69]:
x = np.random.randn(10,10)

In [70]:
x[0]

array([ 0.35408726,  0.65021936, -0.67941423, -0.84263675,  1.18250932,
        1.67513278,  0.76703733, -0.73110367,  0.1567034 ,  0.95214077])

In [71]:
x[0][4]

1.1825093203940065

In [73]:
x[1::2,:] #odd rows of array

array([[-1.23222068e+00, -5.78395751e-01,  8.70487623e-02,
        -5.79568597e-01,  1.37977373e-01, -5.66478385e-01,
         7.70817910e-01,  1.09835355e-01, -1.60806484e+00,
         4.23995311e-01],
       [-1.25712021e+00, -1.97952431e+00, -1.10146451e-01,
        -1.93127244e+00, -1.83669343e+00,  1.38796691e+00,
         8.80176999e-02, -1.56737007e+00,  5.77704990e-01,
        -1.06072863e+00],
       [-4.45050470e-01, -5.78898663e-01,  1.12638879e+00,
         2.05386420e-01,  1.16266122e+00, -4.02247368e-01,
        -5.61038851e-01, -2.05828034e-03, -1.03624056e+00,
         1.02938848e+00],
       [-2.32755389e-02, -2.88718540e+00, -2.61801952e-01,
         6.31039528e-01, -8.33294180e-01, -1.76725051e+00,
        -1.28216287e+00,  9.49346929e-01,  1.20454403e-01,
         1.96617369e-01],
       [ 5.59054117e-01, -1.29486660e+00,  1.18348831e+00,
        -3.75551086e-01,  7.37151308e-01,  1.07747810e+00,
         2.63179603e-01,  8.99062947e-01, -2.24834362e-01,
        -2.

In [74]:
x[::, :4]

array([[ 0.35408726,  0.65021936, -0.67941423, -0.84263675],
       [-1.23222068, -0.57839575,  0.08704876, -0.5795686 ],
       [-0.83921575,  0.0144008 , -0.87510058, -0.40431038],
       [-1.25712021, -1.97952431, -0.11014645, -1.93127244],
       [ 0.14897575, -1.02828122,  0.05004353,  0.70488883],
       [-0.44505047, -0.57889866,  1.12638879,  0.20538642],
       [-0.9601993 , -1.3944458 , -0.51143124, -1.28392847],
       [-0.02327554, -2.8871854 , -0.26180195,  0.63103953],
       [-2.40724623, -0.94883481, -0.13231684,  0.49020051],
       [ 0.55905412, -1.2948666 ,  1.18348831, -0.37555109]])

In [78]:
#Example : 
eg = np.ones((5,5), dtype = np.int)
eg

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [79]:
eg[1:-1,1:-1] = 0
eg

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [80]:
# Fast element wise array functions

In [96]:
x = np.array([4,9,16,25,36], dtype = np.int)

In [97]:
np.sqrt(x)

array([2., 3., 4., 5., 6.])

In [98]:
np.power(x, 2) #(arr, power_value)

array([  16,   81,  256,  625, 1296], dtype=int32)

In [100]:
y = [7,1,2,3,-1]
np.maximum(x,y) #it will give the element wise max from arrays

array([ 7,  9, 16, 25, 36])

In [102]:
#np.where() is applied to all the elements

In [108]:
salary = np.array([0, -1, 100000, 500000])
salary=np.where(salary<=0, 25000, salary)
salary

array([ 25000,  25000, 100000, 500000])

In [109]:
# Mathematical and statistical Methods

In [110]:
x = np.array([10, 9, 7, 10, 7])

In [111]:
x.mean()

8.6

In [112]:
x.cumsum()

array([10, 19, 26, 36, 43], dtype=int32)

In [113]:
x.cumprod()

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [119]:
y = x>6
y

array([ True,  True,  True,  True,  True])

In [120]:
y.sum()

5

In [121]:
y.any()

True

In [122]:
y.all()

True

In [123]:
y = x>8
y

array([ True,  True, False,  True, False])

In [124]:
y.sum()

3

In [125]:
y.all() #all elements true?

False

In [126]:
y.any() #any element true?

True

In [128]:
x.sort()
x

array([ 7,  7,  9, 10, 10])

In [130]:
np.unique(x)

array([ 7,  9, 10])

In [131]:
# File input Output

In [132]:
#np.save(filename.npy, array) , np.load(filename.npy) , np.savez(filename.npz, array1, array2)
#load will return a dictionary

In [1]:
x=[1,4,5,7]
y=[8,7,9]

In [4]:
np.save('testx', x)

In [136]:
loadx = np.load('testx.npy')
loadx

array([1, 4, 5, 7])

In [21]:
np.savez("testxy", x=x, y=y) # multiple arrays can be saved using savez

In [24]:
loadxy = np.load('testxy.npz')
loadxy.files

['x', 'y']

In [19]:
loadxy['arr_0']

numpy.ndarray

In [162]:
loadxy['arr_1']

array([8, 7, 9])

In [163]:
# linear algebra operations

In [164]:
x=np.random.randn(3,2)
y=np.random.randn(2,3)

In [165]:
x.dot(y)

array([[0.17284491, 0.17423341, 1.78628949],
       [0.61078879, 1.61491505, 4.07138269],
       [0.26746041, 0.74977892, 1.68725418]])

In [166]:
x.transpose()

array([[-3.57858115e-01, -1.16845770e-01, -2.21355284e-03],
       [ 6.84881023e-01,  2.28327675e+00,  9.93992343e-01]])

In [167]:
x.trace() # sum of the diagnols 

1.9254186321299336

In [27]:
np.trace(np.eye(5))

5.0

In [168]:
#Pseudo random number generator'

In [169]:
np.random.seed(7)

In [25]:
np.random.normal(size=(3,3))

array([[ 0.69577475,  0.58596671,  0.27905855],
       [-0.00290905, -0.29302355,  1.88986228],
       [-0.96878137, -0.18602707,  0.54589649]])

In [173]:
np.random.uniform(size=(3,3))

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992]])

In [174]:
#Advanced manipulations

In [175]:
#reshape

In [176]:
x=np.random.randn(4,5)
x

array([[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222],
       [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655],
       [-0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936],
       [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088]])

In [178]:
x.reshape((2,2,5), order='F')

array([[[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,
          2.02907222],
        [-0.41647432, -0.74255353,  1.07247013, -1.65107559,
          0.53542936]],

       [[-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,
          1.04939655],
        [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,
          1.76616088]]])

In [179]:
x.reshape((2,2,-1)) # -1 will be replaced by np

array([[[ 0.60049852,  1.65069969,  0.15433554, -0.38713994,
          2.02907222],
        [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,
          1.04939655]],

       [[-0.41647432, -0.74255353,  1.07247013, -1.65107559,
          0.53542936],
        [-2.0644148 , -0.66215934, -1.20421985,  1.46197563,
          1.76616088]]])

In [180]:
x.ravel()

array([ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222,
       -0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655,
       -0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936,
       -2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088])

In [181]:
x.flatten()

array([ 0.60049852,  1.65069969,  0.15433554, -0.38713994,  2.02907222,
       -0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655,
       -0.41647432, -0.74255353,  1.07247013, -1.65107559,  0.53542936,
       -2.0644148 , -0.66215934, -1.20421985,  1.46197563,  1.76616088])

In [182]:
x=[[1,3,5],[7,9,0]]
arr1=np.array(x)

y=[[11,13,15],[17,18,19]]
arr2=np.array(y)

In [184]:
np.concatenate((arr1,arr2), axis=0) # row wise 

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 18, 19]])

In [185]:
np.concatenate((arr1,arr2), axis=1) #column wise

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 18, 19]])

In [186]:
np.vstack((arr1, arr2)) #row wise

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 18, 19]])

In [187]:
np.hstack((arr1, arr2)) # column wise

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 18, 19]])

In [188]:
x = [1,4,5,6,7,9,1,4]
x=np.array(x)

In [189]:
np.split(x, [2,5]) 

[array([1, 4]), array([5, 6, 7]), array([9, 1, 4])]

In [190]:
# start from 0 to first arg then from there this pattern goes on

In [191]:
d=np.array([[1,4,5,6,7,9,1,4],[11,14,15,16,17,19,11,14]])

In [192]:
np.split(d, [4,6], axis=1) # column wise

[array([[ 1,  4,  5,  6],
        [11, 14, 15, 16]]), array([[ 7,  9],
        [17, 19]]), array([[ 1,  4],
        [11, 14]])]

In [194]:
np.split(d, [1], axis=0)

[array([[1, 4, 5, 6, 7, 9, 1, 4]]), array([[11, 14, 15, 16, 17, 19, 11, 14]])]

In [195]:
#tile and repeat

In [201]:
repeater = np.array([6,7,8])
np.repeat(repeater, 3)

array([6, 6, 6, 7, 7, 7, 8, 8, 8])

In [200]:
tiler = np.array([6,7,8])
np.tile(tiler, 3)

array([6, 7, 8, 6, 7, 8, 6, 7, 8])