### array practice (own)
there are six ways to create an array 1)array() 2)linspace() 3)logspace 4)arange() 5)zeros 6)ones()


In [3]:
import numpy as np

In [1]:
from numpy import *
myArr = array([1,2,3,4,5,6])
print(myArr.dtype)


int32


In [12]:
hiarr = linspace(0,15,16) #15 is also included (start,stop,resteps--> break the range into given resteps paths) 
#and as it is divided by 16 so it's float
print(hiarr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [14]:
Arr = arange(0,15,2) #15-1
print(Arr)

[ 0  2  4  6  8 10 12 14]


In [15]:
ourarr = logspace(0,15,16)
print(ourarr) #divided by logs

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09
 1.e+10 1.e+11 1.e+12 1.e+13 1.e+14 1.e+15]


In [23]:
print(sin(Arr))
print(log(Arr))
print(sqrt(Arr))
print(sum(Arr))
print(min(Arr))
print(max(Arr))
print(sort(Arr))
print(concatenate([myArr,Arr]))

[ 0.          0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111
 -0.53657292  0.99060736]
[      -inf 0.69314718 1.38629436 1.79175947 2.07944154 2.30258509
 2.48490665 2.63905733]
[0.         1.41421356 2.         2.44948974 2.82842712 3.16227766
 3.46410162 3.74165739]
56
0
14
[ 0  2  4  6  8 10 12 14]
[ 1  2  3  4  5  6  0  2  4  6  8 10 12 14]


C:\Users\Midhas\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


In [28]:
arr1 = array([1,2,3,4])
arr2 = arr1
print(id(arr1))
print(id(arr2))
arr2[1] = 1
print(arr1)
print(arr2)

1085831726304
1085831726304
[1 1 3 4]
[1 1 3 4]


In [29]:
arr1 = array([1,2,3,4])
arr2 = arr1.view() #to create in another location but still it do shallow copy
print(id(arr1))
print(id(arr2))
arr2[1] = 1 #shallow copy (it changes both)
print(arr1)
print(arr2)

1085831726704
1085831725104
[1 1 3 4]
[1 1 3 4]


In [30]:
arr1 = array([1,2,3,4])
arr2 = arr1.copy()
print(id(arr1))
print(id(arr2))
arr2[1] = 1 #deep copy
print(arr1)
print(arr2)

1085831726784
1085831725584
[1 2 3 4]
[1 1 3 4]


In [73]:
m = matrix('1 2 3 ; 4 5 6')
print(m)
print(diagonal(m))
print(m.min())
print(m.max())


[[1 2 3]
 [4 5 6]]
[1 5]
1
6


In [77]:
m1 = matrix('1 2 3 ; 4 5 6 ; 7 8 9')
m2 = matrix('9 8 7 ; 6 5 4 ; 3 2 1')
m3 = m1 + m2
print(m3)
m4 = m1 * m2 
print(m4)
m5 = m1 @ m2 
print(m5)
#because m4 and m5 are matrix therefore * @ are same but not with array below

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


np.where(condition,option A(if condition is true),option B(when false))

In [2]:
import numpy as np
salary = np.array([0,-1,-2,1000,50000,26000])
np.where(salary<=0,25000,salary)

array([25000, 25000, 25000,  1000, 50000, 26000])

In [10]:
arr = np.arange(12).reshape(3,4)
print(arr)
print(arr.T) #for transpose
#print(arr.transpose((1,0,2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [15]:
myarr = np.array([1,2,1,3,1,3,4,5])
myarr = np.unique(myarr)
print(myarr)
print(np.sort(myarr))

[1 2 3 4 5]
[1 2 3 4 5]


### CLASS 1 Work on numpy

In [2]:
#In list we have to traverse to apply operation
a = [1,2,3,4,5,6,7,8,9,10]
mylist = []

In [35]:
%time
for i in a:
    mylist.append(i*5)

Wall time: 0 ns


In [36]:
print(mylist)

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


In [37]:
print(hex(id(mylist[0])))
print(hex(id(mylist[1])))

0x7ffa5fe793c0
0x7ffa5fe79460


In [38]:
#in numpy we dont have to traverse and apply for loop
import numpy as np

In [39]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [40]:
print(hex(id(a[0])))
print(hex(id(a[1])))

0xfcd16d8ac8
0xfcd16d8ac8


In [41]:
a*5 

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [42]:
import numpy as np
%time 
a = np.array([1,2,3,4,5,6,7,8,9,10])
a*5

Wall time: 0 ns


array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [43]:
numArray = np.array([22,44,55,66]) 
print(numArray)
print(type(numArray))

[22 44 55 66]
<class 'numpy.ndarray'>


In [44]:
numArray = np.array([22,44,55,66],dtype= 'float32') #sb numbers decimal main agye and float should be passed as a string
print(numArray)
print(type(numArray))

[22. 44. 55. 66.]
<class 'numpy.ndarray'>


In [45]:
numArray = np.array([22.1,44.5,55.4,66.2],dtype= 'int32') 
print(numArray)
print(type(numArray))

[22 44 55 66]
<class 'numpy.ndarray'>


In [46]:
numArray = np.array([22.1,44.5,55.4,66.2],dtype= np.int8) 
print(numArray)
print(type(numArray))

[22 44 55 66]
<class 'numpy.ndarray'>


In [47]:
randomArray = np.random.randint(10)
randomArray

3

In [48]:
randomray = np.random.randn(10)*100 #normal distribution
randomray

array([ -59.9102808 ,   97.66432757,  -77.08934665,  -68.5431183 ,
        -23.14778435,  -25.76420756,  -87.66720478, -147.7054981 ,
         40.85119055, -153.737784  ])

In [49]:
randomray.ndim #dimension of array is 1D it is one dimensional vector

1

In [50]:
randomray.shape #the no. of elements give shape or columns , it gives a tupple

(10,)

In [51]:
twoD = np.array([[1,2,3],[4,5,6],[7,8,9],[2,3,4]]) #[] row #in ky andar numbers ki counting are columns
twoD

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4]])

In [52]:
twoD.shape

(4, 3)

In [53]:
zeroD = np.array(100) #idhar srf number pass krwadia hai idhar koi array thori h means [] numbers nhi dye
zeroD.ndim

0

In [54]:
zeroD.shape #since it is scalar it has zero dimension and no shape

()

In [55]:
miscD = np.array([99])
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[99]
1
(1,)


In [56]:
miscD = np.array([[99]]) #now it is a matrix with 2 dimension
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[99]]
2
(1, 1)


In [4]:
miscD = np.array([[[99]]])
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[99]]]
3
(1, 1, 1)


In [58]:
a = np.arange(10) #vector
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a = np.arange(12).reshape(4,3) #vector ko reshape krk dimension barha di or tensor(matrix) banadia
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:

flat = np.ravel(a) #wapis vector bnany k lye ravel krdia
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
flat = flat.reshape(12) #wapis aisy b krskty hn
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
#now if we want to convert twoD to threeD and then convert it again into 2D then
two_D = np.arange(36).reshape(6,6)
two_D

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [63]:
three_D = two_D.reshape(3,3,4)
three_D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [64]:
rebacktwoD = three_D.reshape(6,6)
rebacktwoD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [65]:
threeD = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[3,6,8],[8,7,6],[9,8,7]]])
threeD

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[3, 6, 8],
        [8, 7, 6],
        [9, 8, 7]]])

In [67]:
two_D + two_D #mirror addition (har element apni position k sth add) mirror k lye zorri hai shape same ho

matrix([[ 0,  2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20, 22],
        [24, 26, 28, 30, 32, 34],
        [36, 38, 40, 42, 44, 46],
        [48, 50, 52, 54, 56, 58],
        [60, 62, 64, 66, 68, 70]])

In [69]:
two_D - two_D

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [70]:
two_D / two_D

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [88]:
two_D * two_D #it does mirror multiplication

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [72]:
three_D * two_D #it does mirror multiplication but shape same nhi to error

ValueError: operands could not be broadcast together with shapes (3,3,4) (6,6) 

In [74]:
m1 = np.arange(12).reshape(4,3)

In [75]:
m2 = np.arange(16).reshape(4,4)

In [76]:
m1 + m2 #error because both have different shape

ValueError: operands could not be broadcast together with shapes (4,3) (4,4) 

In [79]:
m3 = np.arange(18).reshape(3,6)
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [84]:
m3 @ m1

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 6)

In [83]:
m1 @ m3 #idhar multiply mirror nhi islye @ lagaya yahan multiply rule follow hoga

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [89]:
np.dot(m1,m3)

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [90]:
m1 * m3 #this is error q k mirror main * use hota hai 

ValueError: operands could not be broadcast together with shapes (4,3) (3,6) 

In [93]:
zeeeros = np.zeros(4)
zeeeros

array([0., 0., 0., 0.])

In [94]:
zeeeros = np.zeros(4,dtype = 'int8')
zeeeros

array([0, 0, 0, 0], dtype=int8)

In [98]:
zeros2D = np.zeros((4,3),dtype = 'int8')
zeros2D

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [96]:
onees = np.ones(4)
onees

array([1., 1., 1., 1.])

In [99]:
onees = np.ones((5,5),dtype = 'int8')
onees

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [100]:
onees * 50

array([[50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50]], dtype=int8)

In [102]:
fulll = np.full((5,5),50) #full is built-in yeh pehle ones bnayega phr multiply ka parameter denge same wohi kam hai 
fulll

array([[50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50]])

In [104]:
emptyy = np.empty((4,4,4)) #garbage values dega -->wo values jo chli jati hain or memory ma value rkhi wi hai refernce nhi h
emptyy

array([[[0.00000000e+000, 1.24339805e-312,             nan,
         0.00000000e+000],
        [6.95264577e-310, 7.90505033e-323, 1.24345609e-312,
         1.24308992e-312],
        [1.24306195e-312, 1.24308961e-312, 0.00000000e+000,
         1.24324987e-312],
        [0.00000000e+000, 0.00000000e+000, 4.94065646e-324,
         0.00000000e+000]],

       [[1.22014758e-311, 0.00000000e+000, 7.55430502e-312,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+0

In [106]:
like = np.zeros_like(m3)
like

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [107]:
likee = np.ones_like(m2)
likee

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
i = np.eye(3,3) #identity matrix jiskay diagonal same hotay hn
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [113]:
j = i.astype("int") #changes
j

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# BASIC INDEXING AND SLICING

In [118]:
aList = [99,77,55,33,11]
type(aList[0:3])
#slicing main jis datatype ko slice kia tou usi ka slice ayega like list ko slice kia tou list hi ayegi

list

In [117]:
type(aList[0]) #or isse ek integer ayega

int

In [4]:
tDarray = np.arange(36).reshape(6,6)
tDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [5]:
tDarray[3,2] #indexing

20

In [6]:
tDarray[3][2] #another way to do indexing

20

In [7]:
#tDarray[row,column] #slicing main 2D hai tou do part bnalo ek row k lye ek column
#tDarray[start:end,start:end]
tDarray[2:5,1:4] #ab slice 2D hi hoga jitna pehle matrix ki dimension utna hi dimension 

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [8]:
tDarray[5:,3:4]

array([[33]])

In [9]:
tDarray[1:2,2:5]

array([[ 8,  9, 10]])

In [14]:
tDarray[1] #1st row 

array([ 6,  7,  8,  9, 10, 11])

In [17]:
arr3d = np.array([[[100,200,300],[400,500,600],[700,800,900]]])
arr3d

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [22]:
arr3d[1] #error coz it is reading 2D or 2D total 1 hai mtlb '0'

IndexError: index 1 is out of bounds for axis 0 with size 1

In [20]:
arr3d[0][2]

array([700, 800, 900])

In [24]:
arr3d[0][2][2]

900

In [25]:
arr3d[0,2,2] #another method

900

In [23]:
np.shape(arr3d) #total no. of 2Ds,3 rows,3 columns

(1, 3, 3)

In [28]:
arr3d = np.array([[[100,200,300],[400,500,600],[700,800,900]],[[1,2,3],[5,6,7],[8,9,10]]])
arr3d

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]],

       [[  1,   2,   3],
        [  5,   6,   7],
        [  8,   9,  10]]])

In [30]:
arr3d[0,:2] #0 is for 2D mtlb hum 0th 2D main agye hn

array([[100, 200, 300],
       [400, 500, 600]])

In [29]:
arr3d[0,:2,1:]

array([[200, 300],
       [500, 600]])

In [43]:
oarr = np.array([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[6,6,1,5,3],[7,5,1,6,5],[8,2,4,9,7]])
oarr

array([[ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5],
       [ 4,  0,  6,  2,  5],
       [ 6,  6,  1,  5,  3],
       [ 7,  5,  1,  6,  5],
       [ 8,  2,  4,  9,  7]])

In [44]:
oarr[2:4,1:4]

array([[0, 6, 2],
       [6, 1, 5]])

In [56]:
aarr = np.arange(1,37).reshape(6,6)
aarr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [61]:
aarr[2:4,2:5]

array([[15, 16, 17],
       [21, 22, 23]])

## Again explanation

In [62]:
aarr = np.arange(1,37).reshape(6,6)
aarr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [63]:
aarr[2:3,]

array([[13, 14, 15, 16, 17, 18]])

In [64]:
aarr[2:3,0:6] #2nd way

array([[13, 14, 15, 16, 17, 18]])

In [65]:
aarr[2:3,:] #3rd way

array([[13, 14, 15, 16, 17, 18]])

In [66]:
aarr[:,2] #idhar : lgana zrori h 

array([ 3,  9, 15, 21, 27, 33])

In [68]:
aarr[1:5]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [73]:
aarr[2:4,5] #in vector form

array([18, 24])

In [75]:
aarr[2:4,5:] 

array([[18],
       [24]])

In [74]:
aarr[2:4,-1]

array([18, 24])

In [78]:
aarr[:,::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [80]:
arr = [1,2,3,4,5]
arr[0:5:2]

[1, 3, 5]

In [82]:
aarr[::2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])